name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/Bush2021/chrome_installer.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout dev
        git merge upstream/dev --allow-unrelated-histories || true

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/opamoy/chrome_installer.git dev
